from dependencies import *

FRAMERATE = 60
AIM_INDICATOR_DISTANCE_FROM_PLAYER = 50
OFFSET_OF_GUN_FROM_PLAYER = pygame.Vector2(0,0)
WEAPON_CAP_AMOUNT = 6
WEAPON_SPAWN_RATE_IN_MILLIS = 10_000

PLAYER_ACCELERATION_RATE = 2
PLAYER_FRICTION = -0.8
PLAYER_MAX_VELOCITY = 8

PLAYER_SPEED = 200
